volumes:
  pg-data:
  redis-data:
    driver: local

services:
  nest-js-api:
    build:
      context: .
      dockerfile: api/docker/nest-js/Dockerfile
      target: dev
      args:
        BASE_IMAGE: ${BASE_IMAGE_NODE}
    environment:
      - APPLICATION_MODE=development
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE
      - CORS_ALLOW_ORIGIN
      - FILE_UPLOAD_FOLDER
      - API_PUBLICATION_MAIL_TO
      - IDENTITY_ISSUER
      - IDENTITY_CLIENT_ID
      - IDENTITY_CLIENT_SECRET
      - IDENTITY_AUTHORIZATION_URL
      - IDENTITY_TOKEN_URL
      - IDENTITY_USER_INFO_URL
      - IDENTITY_CALLBACK_URL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FRONTEND_URL
      - REDOC_USERNAME
      - REDOC_PASSWORD
      - PERUN_URL
      - PERUN_USER
      - PERUN_PASSWORD
      - OPENSTACK_REPO_PATH
      - OPENSTACK_ALLOWED_DOMAINS
      - OPENSTACK_GIT_BASE_BRANCH
      - OPENSTACK_GIT_TARGET_BRANCH
      - OPENSTACK_GIT_AUTHOR_NAME
      - OPENSTACK_GIT_AUTHOR_EMAIL
      - OPENSTACK_GITLAB_PROJECT_ID
      - OPENSTACK_GITLAB_HOST
      - OPENSTACK_GITLAB_TOKEN
    expose:
      - 3000
    volumes:
      - ./shared:/app/shared
      - ./api/uploads:/app/api/uploads
      - ./api/src:/app/api/src
      - ./api/config:/app/api/config
      - ./api/package.json:/app/api/package.json
      - ./api/package-lock.json:/app/api/package-lock.json
      - ./.git:/app/.git
    depends_on:
      - postgres
    networks:
      common:
        aliases:
          - nestjs.resource-manager

  nest-js-cli:
    profiles:
      - cli
    build:
      context: .
      dockerfile: cli/docker/nest-js/Dockerfile
      target: dev
      args:
        BASE_IMAGE: ${BASE_IMAGE_NODE}
    environment:
      - APPLICATION_MODE=development
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE
      - API_URL
    volumes:
      - ./shared:/app/shared
      - ./cli/src:/app/cli/src
    depends_on:
      - postgres
    networks:
      common:
        aliases:
          - nestjs-cli.resource-manager


  postgres:
    image: ${BASE_IMAGE_POSTGRES}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /pg-data
    volumes:
      - pg-data:/pg-data
    networks:
      common:
        aliases:
          - postgres.resource-manager
          - postgres

  redis:
    image: ${BASE_IMAGE_REDIS}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    networks:
      common:
        aliases:
          - redis.resource-manager
          - redis

  proxy:
    build:
      context: ./proxy
      args:
        BASE_IMAGE: ${BASE_IMAGE_NGINX}
    environment:
      - API_PROXY_PASS="http://nest-js-api:3000"
      - EXTERNAL_API_PORT_HTTP=${EXTERNAL_API_PORT_HTTP}
    depends_on:
      - nest-js-api
    ports:
      - target: 3000
        published: ${EXTERNAL_API_PORT_HTTP}
    networks:
      common:
        aliases:
          - api.resource-manager.lab

networks:
  common:
    driver: bridge
